<?xml version="1.0"?>
<!DOCTYPE associations[
	<!ELEMENT associations (association+)>
	<!ELEMENT association (type, image)>
	<!ELEMENT type (#PCDATA)>
	<!ELEMENT image (#PCDATA)>
	<!ATTLIST associations defaultFolderImage CDATA #REQUIRED>
	<!ATTLIST associations defaultLeafImage CDATA #REQUIRED>
]>
<associations defaultFolderImage="folder.gif" defaultLeafImage="leaf.gif">
	<association>
		<type>Buildings</type>
		<image>building.gif</image>
	</association>
	<association>
		<type>Rooms</type>
		<image>groups.gif</image>
	</association>	
	<association>
		<type>Nodes</type>
		<image>node.gif</image>
	</association>
</associations>
